project_id = "fewysenbjhxhqwocttvv"

[functions.send-task-reminders]
verify_jwt = false

[functions.send-habit-reminders]
verify_jwt = false

[functions.send-family-event-reminders]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.microsoft-calendar-sync]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-loan-reminders]
verify_jwt = false

[functions.send-smtp-email]
verify_jwt = false

[functions.save-calendar-credentials]
verify_jwt = false

[functions.send-task-assignment-notification]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false
